#!/bin/bash
# ============================================================
# Script 5: Open Source Manifesto Generator
# Author: Sara | Reg No: 24BSA10335 | Course: Open Source Software
# Software Choice: Git
# Description: Asks 3 interactive questions, then writes a
#              personalised open source philosophy statement
#              to a .txt file using string concatenation.
# ============================================================

# --- Aliases concept (demonstrated via comment + function) ---
# In a real shell session you'd write: alias gs='git status'
# Here we simulate it as a function to keep the script portable
gitlog_alias() {
    # This acts like: alias gl='git log --oneline -5'
    git log --oneline -5 2>/dev/null || echo "(not inside a git repo)"
}

# --- Welcome banner ---
echo "======================================================="
echo "       Open Source Manifesto Generator"
echo "       Powered by: Git & Bash | GPL v2"
echo "======================================================="
echo ""
echo "Answer three questions and your manifesto will be"
echo "written to a file — freely shareable, like all good"
echo "open source work."
echo ""

# ============================================================
# read: interactive user input (3 questions)
# -p flag prints a prompt on the same line
# ============================================================

read -p "1. Name one open-source tool you use every day: " TOOL
echo ""

read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
echo ""

read -p "3. Name one thing you would build and share freely: " BUILD
echo ""

# --- Input validation: make sure none are empty ---
if [ -z "$TOOL" ] || [ -z "$FREEDOM" ] || [ -z "$BUILD" ]; then
    echo "❌  Please answer all three questions. Try again."
    exit 1
fi

# --- Date and output filename ---
DATE=$(date '+%d %B %Y')                    # e.g., 15 April 2025
OUTPUT="manifesto_$(whoami).txt"            # e.g., manifesto_john.txt

# ============================================================
# String concatenation: build the manifesto paragraph
# Each echo >> appends a new line to the output file
# Using > first to create/overwrite, then >> to append
# ============================================================

# Overwrite (or create) the file with the header
echo "=======================================================" > "$OUTPUT"
echo "  MY OPEN SOURCE MANIFESTO" >> "$OUTPUT"
echo "  Generated on: $DATE" >> "$OUTPUT"
echo "  Author: $(whoami)" >> "$OUTPUT"
echo "=======================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- The manifesto paragraph (string concatenation across lines) ---
echo "Every day, I rely on $TOOL — a piece of software that" >> "$OUTPUT"
echo "someone built and chose to share with the world for free." >> "$OUTPUT"
echo "Not free as in free beer, but free as in $FREEDOM." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Open source is the reason I can read, modify, and trust" >> "$OUTPUT"
echo "the tools I use. It is how Linus Torvalds gave the world" >> "$OUTPUT"
echo "Linux, and how Git itself was born in a single weekend" >> "$OUTPUT"
echo "because Linus refused to let a proprietary tool control" >> "$OUTPUT"
echo "his work. That spirit matters." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "I believe that when I build something, I have a choice:" >> "$OUTPUT"
echo "hoard it, or share it. I choose to share." >> "$OUTPUT"
echo "Someday, I want to build $BUILD — and release it freely," >> "$OUTPUT"
echo "so that someone I will never meet can build something" >> "$OUTPUT"
echo "better on top of it." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "That is what open source means to me: $FREEDOM." >> "$OUTPUT"
echo "" >> "$OUTPUT"

# --- Footer ---
echo "-------------------------------------------------------" >> "$OUTPUT"
echo "  This manifesto was generated by an open source" >> "$OUTPUT"
echo "  Bash script. You are free to copy, modify, and" >> "$OUTPUT"
echo "  share it. No permission required." >> "$OUTPUT"
echo "  (GPL v2 — just like Git itself)" >> "$OUTPUT"
echo "=======================================================" >> "$OUTPUT"

# --- Show result ---
echo ""
echo "✅  Manifesto saved to: $OUTPUT"
echo ""
echo "--- Your Manifesto ---"
echo ""
cat "$OUTPUT"   # Display the file contents

echo ""
echo "--- Your recent Git history (alias demo) ---"
gitlog_alias

echo ""
echo "======================================================="
echo " Share your manifesto: cat $OUTPUT | pbcopy"
echo " (pbcopy copies it to your Mac clipboard!)"
echo "======================================================="
